trigger:
- master

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'Build'
    jobs:
      - job: 'build'
        steps:
          - template: templates/build-steps.yml
            parameters:
              buildConfiguration: $(buildConfiguration)
          - task: DotNetCoreCLI@2
            displayName: 'install ef tool'
            inputs:
              command: 'custom'
              custom: 'tool'
              arguments: 'install --global dotnet-ef'
          - task: DotNetCoreCLI@2
            displayName: 'generate catalogdb sql'
            inputs:
              command: 'custom'
              custom: 'ef'
              arguments: 'migrations script -c catalogcontext -p $(System.DefaultWorkingDirectory)\src\Infrastructure\Infrastructure.csproj -s $(System.DefaultWorkingDirectory)\src\Web\Web.csproj -i -o $(System.DefaultWorkingDirectory)\sql\catalogdb.sql'
          - task: DotNetCoreCLI@2
            displayName: 'generate identitydb sql'
            inputs:
              command: 'custom'
              custom: 'ef'
              arguments: 'migrations script -c appidentitydbcontext -p $(System.DefaultWorkingDirectory)\src\Infrastructure\Infrastructure.csproj -s $(System.DefaultWorkingDirectory)\src\Web\Web.csproj -i -o $(System.DefaultWorkingDirectory)\sql\identitydb.sql'
          - task: DotNetCoreCLI@2
            displayName: 'package web-site'
            inputs:
              command: publish
              publishWebProjects: True
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: True
          - task: CopyFiles@2
            displayName: Copy Dacpac
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)'
              Contents: '**\bin\$(BuildConfiguration)\*.dacpac'
              flattenFolders: true
              TargetFolder: '$(build.artifactStagingDirectory)\sql'

          - task: PowerShell@2
            displayName: "Deploy dacpac to localdb"
            inputs:
              targetType: 'inline'
              script: 'sqlpackage.exe 
          - task: CmdLine@2
            inputs:
              script: '"C:\Program Files (x86)\Microsoft SQL Server\140\Dac\bin\SqlPackage.exe" "/action:publish" "/TargetFile:$(build.artifactStagingDirectory)/sql/Database.dacpac" "/SourceConnectionString:Server=(localdb)\MSSQLLocalDB;Database=eShopDb;Trusted_Connection=True;"''
          - task: PublishBuildArtifacts@1
            displayName: 'publish web-site'
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
              artifactName: 'eshoponweb-site'
          - task: PublishBuildArtifacts@1
            displayName: 'publish scripts'
            inputs:
              pathtoPublish: '$(System.DefaultWorkingDirectory)\scripts' 
              artifactName: 'eshoponweb-scripts'
          - task: PublishBuildArtifacts@1
            displayName: 'publish sql'
            inputs:
              pathtoPublish: '$(System.DefaultWorkingDirectory)\sql' 
              artifactName: 'eshoponweb-sql'
  - stage: 'Staging'
    jobs:
      - template: templates/deployment-job.yml
        parameters:
          environmentName: 'staging'
          azureSubscription: 'azure-vs-enterprise'
          