trigger: none

pr:
  - master

pool:
  vmImage: 'vs2017-win2016'

variables:
  solution: 'eShopOnWeb.sln'

steps:
  - template: templates/build-steps.yml
    parameters:
      buildConfiguration: 'Release'