trigger:
- master

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'Build'
    jobs:
      - job: 'build'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'restore nuget packages'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            displayName: 'build solution'
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              arguments: '--configuration $(buildConfiguration)'
          - task: DotNetCoreCLI@2
            displayName: 'run unit tests'
            inputs:
              command: 'test'
              projects: 'tests/UnitTests/*.csproj'
              arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
          - task: DotNetCoreCLI@2
            displayName: 'run integration tests'
            inputs:
              command: 'test'
              projects: 'tests/IntegrationTests/*.csproj'
              arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
          - task: DotNetCoreCLI@2
            displayName: 'package web-site'
            inputs:
              command: publish
              publishWebProjects: True
              arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: True
          - task: PublishBuildArtifacts@1
            displayName: 'publish web-site'
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
              artifactName: 'eshoponweb-site'
          - task: PublishBuildArtifacts@1
            displayName: 'publish iac'
            inputs:
              pathtoPublish: '$(System.DefaultWorkingDirectory)\iac' 
              artifactName: 'eshoponweb-iac'
  - stage: 'Deployment'
    jobs:
      - deployment: 'deploy'
        variables:
          - group: aadev-configuration
        environment: 'aadev'
        strategy:
          runOnce:
            deploy:
              steps:
              - download: current
                displayName: 'download eshoponweb-iac'
                artifact: eshoponweb-iac
              - download: current
                displayName: 'download eshoponweb-site'
                artifact: eshoponweb-site
              - task: AzureCLI@2
                displayName: 'provision azure resources'
                inputs:
                  azureSubscription: 'azure-vs-enterprise'
                  scriptType: 'pscore'
                  scriptLocation: 'scriptPath'
                  scriptPath: '$(Pipeline.Workspace)\eshoponweb-iac\provision-azure-resources.ps1'
                  arguments: '-Environment $(Environment.Name)'
              - task: AzureWebApp@1
                displayName: 'deploy azure appservice'
                inputs:
                  appType: webApp
                  azureSubscription: 'azure-vs-enterprise'
                  appName: 'eshoponweb-aadev-as'
                  package: $(Pipeline.Workspace)/eshoponweb-site/*.zip
                  appSettings: '-ConnectionStrings.CatalogConnection $(eshoponwebdbpwd)'