trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'Build'
    jobs:
      - job: 'build'
        steps:
          - task: DotNetCoreCLI@2
            displayName: 'restore nuget packages'
            inputs:
              command: 'restore'
              projects: '**/*.csproj'
              feedsToUse: 'select'
          - task: DotNetCoreCLI@2
            displayName: 'build solution'
            inputs:
              command: 'build'
              projects: '**/*.csproj'
              configuration: $(buildConfiguration)
          - task: DotNetCoreCLI@2
            displayName: 'run unit tests'
            inputs:
              command: 'test'
              projects: 'tests/UnitTests/*.csproj'
          - task: DotNetCoreCLI@2
            displayName: 'run integration tests'
            inputs:
              command: 'test'
              projects: 'tests/IntegrationTests/*.csproj'

