trigger:
- master

pr: none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
  - stage: 'Build'
    jobs:
      - job: 'build'
        steps:
          - template: templates/build-steps.yml
            parameters:
              buildConfiguration: $(buildConfiguration)
          - script: 'dotnet ef migrations script -c catalogcontext -p src/Infrastructure/Infrastructure.csproj -s src/Web/Web.csproj -i -o $(System.DefaultWorkingDirectory)/sql/catalogdb.sql'
          - script: 'dotnet ef migrations script -c appidentitydbcontext -p src/Infrastructure/Infrastructure.csproj -s src/Web/Web.csproj -i -o $(System.DefaultWorkingDirectory)/sql/identitydb.sql'
          - task: DotNetCoreCLI@2
            displayName: 'package web-site'
            inputs:
              command: publish
              publishWebProjects: True
              arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
              zipAfterPublish: True
          - task: PublishBuildArtifacts@1
            displayName: 'publish web-site'
            inputs:
              pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
              artifactName: 'eshoponweb-site'
          - task: PublishBuildArtifacts@1
            displayName: 'publish scripts'
            inputs:
              pathtoPublish: '$(System.DefaultWorkingDirectory)\scripts' 
              artifactName: 'eshoponweb-scripts'
          - task: PublishBuildArtifacts@1
            displayName: 'publish sql'
            inputs:
              pathtoPublish: '$(System.DefaultWorkingDirectory)\sql' 
              artifactName: 'eshoponweb-sql'
  - stage: 'Staging'
    jobs:
      - template: templates/deployment-job.yml
        parameters:
          environmentName: 'staging'
          azureSubscription: 'azure-vs-enterprise'
          