parameters:
- name: environmentName
  type: string
- name: azureSubscription
  type: string
jobs:
  - deployment: 'deploy'
    variables:
      - group: '${{ parameters.environmentName }}-settings' # Expect a variable group with envrionment-settings that includes all variables
    environment: '${{ parameters.environmentName }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            displayName: 'download eshoponweb-iac'
            artifact: eshoponweb-iac
          - download: current
            displayName: 'download eshoponweb-site'
            artifact: eshoponweb-site
          - task: AzureCLI@2
            displayName: 'provision azure resources'
            inputs:
              azureSubscription: '${{ parameters.azureSubscription }}'
              scriptType: 'pscore'
              scriptLocation: 'scriptPath'
              scriptPath: '$(Pipeline.Workspace)\eshoponweb-iac\provision-azure-resources.ps1'
              arguments: '-Environment ${{ parameters.environmentName }}'
          - task: AzureWebApp@1
            displayName: 'deploy azure appservice'
            inputs:
              appType: webApp
              azureSubscription: 'azure-vs-enterprise'
              appName: 'eshoponweb-${{ parameters.environmentName }}-as'
              package: $(Pipeline.Workspace)/eshoponweb-site/*.zip
              appSettings: '-ConnectionStrings.CatalogConnection $(connectionString)'