parameters:
- name: environmentName
  type: string
- name: azureSubscription
  type: string
jobs:
  - deployment: 'deploy'
    variables:
      - group: '${{ parameters.environmentName }}-settings' # Expect a variable group with envrionment-settings that includes all variables
    environment: '${{ parameters.environmentName }}'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '3.1.x'
          - download: current
            displayName: 'download eshoponweb-iac'
            artifact: eshoponweb-scripts
          - download: current
            displayName: 'download eshoponweb-site'
            artifact: eshoponweb-site
          - download: current
            displayName: 'download eshoponweb-sql'
            artifact: eshoponweb-sql
          - task: AzureCLI@2
            displayName: 'provision azure resources'
            inputs:
              azureSubscription: '${{ parameters.azureSubscription }}'
              scriptType: 'pscore'
              scriptLocation: 'scriptPath'
              scriptPath: '$(Pipeline.Workspace)\eshoponweb-scripts\provision-azure-resources.ps1' # will set connection strings to variables
              arguments: '-Environment ${{ parameters.environmentName }} -SqlAdminUserName $(SqlAdminUserName) -SqlAdminPassword $(SqlAdminPassword)'
          - task: SqlAzureDacpacDeployment@1
            inputs:
              azureSubscription: '${{ parameters.azureSubscription }}'
              AuthenticationType: 'connectionString'
              ConnectionString: '$(catalogConnectionString)'
              deployType: 'SqlTask'
              SqlFile: '$(Pipeline.Workspace)/eshoponweb-sql/catalogdb.sql'
              IpDetectionMethod: 'AutoDetect'
          - task: SqlAzureDacpacDeployment@1
            inputs:
              azureSubscription: '${{ parameters.azureSubscription }}'
              AuthenticationType: 'connectionString'
              ConnectionString: '$(identityConnectionString)'
              deployType: 'SqlTask'
              SqlFile: '$(Pipeline.Workspace)/eshoponweb-sql/identitydb.sql'
              IpDetectionMethod: 'AutoDetect'
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '${{ parameters.azureSubscription }}'
              appType: 'webApp'
              WebAppName: 'eshoponweb-${{ parameters.environmentName }}-as'
              packageForLinux: '$(Pipeline.Workspace)/eshoponweb-site/Web.zip'
              AppSettings: '-ConnectionStrings.CatalogConnection "$(catalogConnectionString)" -ConnectionStrings.IdentityConnection "$(identityConnectionString)"'